apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::991599208796:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AMYAJTK3X1MI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::991599208796:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-10-17T18:01:02Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
      manager: vpcLambda
      operation: Update
      time: "2021-10-17T18:01:02Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:mapRoles: {}
      manager: kubectl-patch
      operation: Update
      time: "2021-10-17T19:09:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8625"
  uid: b1a0c86b-18a7-4ea8-94e0-13dfa2a6fda1
